### ISSUE TITLE
problem with danish characters

### ISSUE THREAD

**Issue by helmuthm** [php-fusion/Addons#11]
points_system/infusions/points_panel/locale/Danish.php

the Danish characters Æ, æ, Ø, ø, Å, å are converted wrongly

please fix the problem

**Comment by RobiNN1** [comment]
because you are not using utf-8

**Comment by helmuthm** [comment]
please tell me if this is the right setting or not:

![unicode-1](https://user-images.githubusercontent.com/9512774/50547172-14023600-0c35-11e9-8faf-8caac9cfabfb.png)

**Comment by RobiNN1** [comment]
![screen](https://user-images.githubusercontent.com/11664877/50547191-7e1adb00-0c35-11e9-8687-671577d0a394.png)
...

**Comment by RobiNN1** [comment]
you need conver files to utf-8

"default encoding for **new** documents"

**Comment by RobiNN1** [comment]
solved?
