### ISSUE TITLE
cv_qr_code_panel

### ISSUE THREAD

**Issue by jonathanwichter** [php-fusion/Addons#4]
<img width="1147" alt="screen shot 2018-06-21 at 8 38 12 am" src="https://user-images.githubusercontent.com/35083828/41719582-75aa555c-752e-11e8-8019-3ba21a946cd8.png">

**Comment by RobiNN1** [comment]
Fixed, but still contains lot of bugs. I recommend not to use.

**Comment by jonathanwichter** [comment]
Yea I saw that my error panel was filled lol
